In [175]:
import pandas as pd
import numpy as np

df = pd.read_csv("videosUS.csv")

df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22.0,2017-11-13T17:13:01.000Z,SHANtell martin,748374.0,57527.0,2966.0,15954.0,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24.0,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783.0,97185.0,6146.0,12703.0,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John..."
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23.0,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434.0,146033.0,5339.0,8181.0,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,puqaWrEC7tY,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24.0,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168.0,10172.0,666.0,2146.0,https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg,False,False,False,Today we find out if Link is a Nickelback amat...
4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24.0,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731.0,132235.0,1989.0,17518.0,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...

In [176]:
#Displaying the missing data
df.isna()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41410,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
41411,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
41412,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
41413,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
41414,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [177]:
#Displaying the sum of missing values within the dataset
df.isnull().sum()

video_id                     0
trending_date              466
title                      466
channel_title              466
category_id                466
publish_time               466
tags                       466
views                      466
likes                      466
dislikes                   466
comment_count              466
thumbnail_link             466
comments_disabled          466
ratings_disabled           466
video_error_or_removed     466
description               1036
dtype: int64

In [178]:
#The number of missing values within the dataset
total = df.isna().sum().sum()
print("The number of missing values within the dataset is",total)

The number of missing values within the dataset is 7560

We may have these missing values because the dataset was corrupted during a transfer and some data went missing (Missing Completely at Random (MCAR)).

In [179]:
#The list of columns with missings values within the dataset
df.loc[:, df.isnull().any()].columns

Index(['trending_date', 'title', 'channel_title', 'category_id',
       'publish_time', 'tags', 'views', 'likes', 'dislikes', 'comment_count',
       'thumbnail_link', 'comments_disabled', 'ratings_disabled',
       'video_error_or_removed', 'description'],
      dtype='object')

In [181]:
#The mean, median, quartiles of each numerical variable within the dataset
describe = df.describe()
describe

        category_id         views         likes      dislikes  comment_count
count  40949.000000  4.094900e+04  4.094900e+04  4.094900e+04   4.094900e+04
mean      19.972429  2.360785e+06  7.426670e+04  3.711401e+03   8.446804e+03
std        7.568327  7.394114e+06  2.288853e+05  2.902971e+04   3.743049e+04
min        1.000000  5.490000e+02  0.000000e+00  0.000000e+00   0.000000e+00
25%       17.000000  2.423290e+05  5.424000e+03  2.020000e+02   6.140000e+02
50%       24.000000  6.818610e+05  1.809100e+04  6.310000e+02   1.856000e+03
75%       25.000000  1.823157e+06  5.541700e+04  1.938000e+03   5.755000e+03
max       43.000000  2.252119e+08  5.613827e+06  1.674420e+06   1.361580e+06

In [182]:
#Spotting the possible outliers in the dataset and get rid of them
df_zscore = (df - df.mean()) / df.std()
df = df[df_zscore < 3]
df

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,NaN,NaN,NaN,NaN,22.0,NaN,NaN,748374.0,57527.0,2966.0,15954.0,NaN,False,False,False,NaN
1,NaN,NaN,NaN,NaN,24.0,NaN,NaN,2418783.0,97185.0,6146.0,12703.0,NaN,False,False,False,NaN
2,NaN,NaN,NaN,NaN,23.0,NaN,NaN,3191434.0,146033.0,5339.0,8181.0,NaN,False,False,False,NaN
3,NaN,NaN,NaN,NaN,24.0,NaN,NaN,343168.0,10172.0,666.0,2146.0,NaN,False,False,False,NaN
4,NaN,NaN,NaN,NaN,24.0,NaN,NaN,2095731.0,132235.0,1989.0,17518.0,NaN,False,False,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41410,NaN,NaN,NaN,NaN,15.0,NaN,NaN,1685609.0,38160.0,1385.0,2657.0,NaN,False,False,False,NaN
41411,NaN,NaN,NaN,NaN,22.0,NaN,NaN,1064798.0,60008.0,382.0,3936.0,NaN,False,False,False,NaN
41412,NaN,NaN,NaN,NaN,24.0,NaN,NaN,1066451.0,48068.0,1032.0,3992.0,NaN,False,False,False,NaN
41413,NaN,NaN,NaN,NaN,1.0,NaN,NaN,5660813.0,192957.0,2846.0,13088.0,NaN,False,False,False,NaN
41414,NaN,NaN,NaN,NaN,20.0,NaN,NaN,10306119.0,357079.0,NaN,NaN,NaN,False,False,False,NaN

In [183]:
#Number of unique categories within the dataset
df['category_id'].nunique()

15

There are columns that we need to adjust their types, these are the non-numerical ones, like the "tags" column. We need to convert them to the numerical type so that we can apply Machine Learning algorithms on them.

In [184]:
#Convert tags to numerical type
df = pd.read_csv("videosUS.csv")

y = pd.get_dummies(df['tags'], prefix='tags')
y

,"tags_#MeToo|""Grammys 2018""|""Janelle Monáe""|""Kesha""","tags_#NeighborDanceChallenge|""#neighbor""|""#dance""|""#loveyourneighbors""|""#dreamer""|""#dancing""|""#musicvideo""|""#love""|""#iphone8""|""#iMovie""|""#iTunes""","tags_#Pride|""#ProudToCreate""|""#ProudToBe""|""#ProudToLove""|""#Pride2018""|""Pride""|""Pride 2018""|""#PrideMonth""|""Adam Rippon""|""Tyler Oakley""|""Janelle Monae""|""Lena Waithe""|""PatrickStarrr""|""ConnerFranta""|""MyHarto""|""Jay Versace""|""Mykki Blanco""|""Big Freedia""|""ASAPScience""|""Hayley Kiyoko""|""Team2Moms""|""TodrickHall""|""Sasha Velour""|""Peppermint""|""Alexis Michelle""|""Aja Kween""|""LGBTQ""|""LGBTQPride""|""youtube""|""proud""|""trans""|""queer""|""lesbian""|""gay""|""pride""",tags_#guitar #musiciseverywhere #jammin #meme #funny #deeppurple #pinkfloyd,"tags_#safarilive|""#safarilive nat geo wild""|""safarilive""|""nat geo wild livestream""|""Maasai Mara""|""wild animals live""|""nat geo wild""|""national geographic""|""wild""|""wildlife""|""animals""|""nat geo""|""natgeo""|""science""|""discover""|""nature""|""documentary""|""explore""|""survival""|""lions""|""zebra""|""gators""|""crocodiles""|""wildebeest""|""elephant""|""giraffes""|""plnxd9fyeqxey0fs9bykxwimyswobm6y6g""|""safari live""|""safari""|""live safari""|""nat geo safari""|""nat geo wild safari live""|""nat geo wild safari""|""safari live stream""|""safari live day 81""|""new cheetah""","tags_#treasure|""scuba diving for treasure""|""finding buried treasure""|""treasure in pond""|""sharer treasure hunt""|""buried treasure""|""finding treasure""|""scuba diving""|""underwater treasure""|""treasure chest""|""we found a treasure""|""scuba diving in pond""|""scuba""|""treasure hunting""|""stephen""|""exploring""|""carter sharer""|""stephen sharer""|""sharer fam""|""sharer bros""|""hunting""|""treasure in lake""|""treasure""|""share the love""|""carter""|""real treasure hunt""","tags_#whopper|""#fastfood""|""#burgers""|""#chocolate""|""#chocolatelovers""|""#foodporn""|""#burgerking""|""#chocolateart""|""#aprilfools""|""#brandaprilfools""","tags_#youtubeblack|""wendy williams""|""the wendy williams show""|""the chi""|""showtime""|""lena waithe""","tags_$1000 Survival Kit|""Survival Kit in a Case""|""pelican case""|""pelican case survival kit""|""emergency survival kit""|""emergency kit""|""$1000""|""$1000 mystery box""|""$1000 survival case""|""unboxing survival box""|""Survival Kit Unboxing""|""unboxing""|""crazyrussianhacker""|""taras kul""","tags_$10|""less than $10""|""living on $10""|""living on $10 a day""|""$10 a day""|""10 dollars""|""ten""|""ten dollars""|""cheap""|""under $10""|""under ten""|""under 10""|""dollar""|""budget""|""gadget""|""under""|""cheapest""|""cheapest hotels""|""cheapest travel""|""cheap travel""|""cheap living""|""backpacking""|""bargain""|""travel tips""|""inexpensive""|""budget travel""|""tourism""|""travel""|""affordable""|""cheapest countries in the world""|""cheapest places to live""|""$10 travel challenge""|""how to travel cheap""|""the infographics show""|""theinfographicsshow""",...,"tags_“truTv|""Shows”""|""”truTV""|""New""|""Series”""|""“trutv""|""episode""|""clips”""|""youtube”""|""“true""|""tv”""|""“truetv”""|""youtube""|""channel”""|""“the""|""new""|""trutv”""|""adam ruins everything""|""ruins everything""|""truTV""|""adam ruins""|""truTv adam ruins everything""|""adam conover""|""adam ruins everything truTV""|""adam conover runis everything""|""Truth""","tags_ニンジャバットマン|""batman ninja""|""batman""|""神風動画""|""水﨑淳平""|""中島かずき""|""岡崎能士""|""DC""|""バットマン""","tags_周杰倫|""Jay""|""Chou""|""周董""|""周杰伦""|""周傑倫""|""杰威尔""|""周周""|""袁詠琳""|""cindy""|""yen""|""官方""|""高清""|""不愛我就拉倒""|""繁體""|""浩克""|""彈頭""","tags_東京サム|""jvlog""|""jvlogger""|""tkyosam""|""tokyo""|""sam""|""japan""|""gaijin""|""vlog""|""japan vlog""|""real talk""|""english""|""teaching""|""in""|""asia""|""black black""|""stay black""|""Tokyo""|""study japanese""|""東京""|""外人""|""tokyosam""|""japanese sushi""|""jiro loves sushi""|""viral japanese video""|""ikebukuro""|""stupid tourists""|""fun in japan""|""japanese conveyor belt sushi""|""eating food""|""japanese food""|""japanese street food""|""seafood""|""sashimi""|""トータルテンボス""|""sushi★boys""|""gopro""|""japanese tourism""","tags_방탄소년단|""BTS""|""2017 MAMA""|""2017마마""|""MAMA""|""마마""|""Mnet""|""엠넷""|""Mnet Asian Music Awards""","tags_방탄소년단|""BTS""|""BANGTAN""|""HIPHOP""|""랩몬스터""|""RapMonster""|""슈가""|""SUGA""|""제이홉""|""jhope""|""지민""|""JIMIN""|""뷔""|""정국""|""JUNGKOOK""|""진""|""JIN""","tags_아리키친|""arikitchen""|""아리키친 젤리""|""회오리젤리""|""jello rollup""","tags_애니멀봐|""동물농장""|""TV동물농장""|""동물농장 애니멀봐""|""애니멀봐 동물농장""","tags_위너|""WINNER""|""이승훈""|""송민호""|""김진우""|""강승윤""|""JINU""|""MINO""|""HOONY""|""YOONY""","tags_종현|""태연""|""jonghyun""|""lonely""|""taeyeon""|""shinee""|""jonghyun lonely""|""hope you rest in peace"""
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41410,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41411,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41412,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41413,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41414,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [192]:
#Number of tags
df['tags'].nunique()

6055

In [191]:
#The most common tags
df['tags'].value_counts().idxmax()

'[none]'